name: browser-svc
description: >-
  A basic browser service for the Amusia project, running on balenaOS.
version:  0.0.1
type: sw.block
assets:
  repository:
    type: blob.asset
    data:
      url: 'https://github.com/k-d-o/amusia_alexithymia/balena/blocks'
  logo:
    type: blob.asset
    data:
      url: 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fmonster.fandom.com%2Fwiki%2FSnark&psig=AOvVaw3ZTt9uO-Kmz_O_629Rdy5J&ust=1745394402782000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCLiim4CT64wDFQAAAAAdAAAAABAE'
data:
  defaultDeviceType: raspberrypi4-64
  supportedDeviceTypes:
    - raspberrypi4-64
    - raspberrypi3
    - raspberrypi3-64
    - raspberrypi400-64
services:
    browser:
      image: bh.cr/balenalabs/browser-aarch64
      privileged: true
      network_mode: host
      environment:
        - LAUNCH_URL
        - KIOSK=true

    
