version: '2'
services:
  browser:
    image: bh.cr/g_kyle_doering/browser
    privileged: true
    # Optional configuration:
    environment:
      - LAUNCH_URL=https://example.com  # Optional: specify URL to display
    # If you need persistence:
    volumes:
      - 'settings:/data'
volumes:
  settings: